# Generated by Django 2.2.5 on 2020-06-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crazy_Minion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
